# Generated by Django 5.0.3 on 2024-03-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_message_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя отправка сообщения'),
        ),
    ]
